class Constants {
  static final categoryList = <Map<String, String>>[
    {'name': 'Headache', 'image': 'assets/images/headache.jpeg'},
    {'name': 'Supplements', 'image': 'assets/images/supplement.jpeg'},
    {'name': 'Infants', 'image': 'assets/images/infants.jpeg'},
    {'name': 'Cough', 'image': 'assets/images/cough.jpeg'},
  ];

  static final itemList = <Map<String, dynamic>>[
    {
      'name': 'Paracetamol',
      'image': 'assets/images/paracetamol1.jpeg',
      'desc': 'Table 500mg',
      'price': '350.00',
      'sold_by': 'Emzor Pharmaciticals',
      'sold_by_image': 'assets/images/emzor.png',
      'pack_size': '8 x 12 tablets(96)',
      'product_id': 'PRO234324234',
      'const': 'Paracetamol',
      'dispensed_in': 'Packs',
      'long_desc':
          '1 pack of Emzor paracetamol (500gm) contains 8 units of 12 tablets',
      'requires_pres': false,
    },
    {
      'name': 'Doliprane',
      'image': 'assets/images/doliprane.jpeg',
      'desc': 'Capsule 1000mg',
      'price': '350.00',
      'sold_by': 'Emzor Pharmaciticals',
      'sold_by_image': 'assets/images/emzor.png',
      'pack_size': '8 x 12 tablets(96)',
      'product_id': 'PRO234324234',
      'const': 'Paracetamol',
      'dispensed_in': 'Packs',
      'long_desc':
          '1 pack of Emzor paracetamol (500gm) contains 8 units of 12 tablets',
      'requires_pres': true,
    },
    {
      'name': 'Paracetamol',
      'image': 'assets/images/paracetamol2.jpeg',
      'desc': 'Table 500mg',
      'price': '350.00',
      'sold_by': 'Emzor Pharmaciticals',
      'sold_by_image': 'assets/images/emzor.png',
      'pack_size': '8 x 12 tablets(96)',
      'product_id': 'PRO234324234',
      'const': 'Paracetamol',
      'dispensed_in': 'Packs',
      'long_desc':
          '1 pack of Emzor paracetamol (500gm) contains 8 units of 12 tablets',
      'requires_pres': true,
    },
    {
      'name': 'Ibuprofen',
      'image': 'assets/images/ibuprofen.jpeg',
      'desc': 'Table 500mg',
      'price': '350.00',
      'sold_by': 'Emzor Pharmaciticals',
      'sold_by_image': 'assets/images/emzor.png',
      'pack_size': '8 x 12 tablets(96)',
      'product_id': 'PRO234324234',
      'const': 'Paracetamol',
      'dispensed_in': 'Packs',
      'long_desc':
          '1 pack of Emzor paracetamol (500gm) contains 8 units of 12 tablets',
      'requires_pres': false,
    },
    {
      'name': 'Panadol',
      'image': 'assets/images/panadol.jpeg',
      'desc': 'Table 400mg',
      'price': '350.00',
      'sold_by': 'Emzor Pharmaciticals',
      'sold_by_image': 'assets/images/emzor.png',
      'pack_size': '8 x 12 tablets(96)',
      'product_id': 'PRO234324234',
      'const': 'Paracetamol',
      'dispensed_in': 'Packs',
      'long_desc':
          '1 pack of Emzor paracetamol (500gm) contains 8 units of 12 tablets',
      'requires_pres': false,
    },
    {
      'name': 'Ibuprofen',
      'image': 'assets/images/ibupro.png',
      'desc': 'Table 500mg',
      'price': '350.00',
      'sold_by': 'Emzor Pharmaciticals',
      'sold_by_image': 'assets/images/emzor.png',
      'pack_size': '8 x 12 tablets(96)',
      'product_id': 'PRO234324234',
      'const': 'Paracetamol',
      'dispensed_in': 'Packs',
      'long_desc':
          '1 pack of Emzor paracetamol (500gm) contains 8 units of 12 tablets',
      'requires_pres': false,
    },
  ];
}
